name: MT3600BE-MINIMAL

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/MT3600BE-MINIMAL.yml'
      - '.github/workflows/WRT-CORE.yml'
      - 'Config/MT3600BE-MINIMAL.txt'
      - 'Scripts/**'

jobs:
  call-core:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_NAME: GL-MT3600BE-MINIMAL
      WRT_REPO: coolsnowwolf/lede
      WRT_BRANCH: master
      WRT_COMMIT: 6c3097f
      DEVICE_CONFIG: Config/MT3600BE-MINIMAL.txt
      GENERAL_CONFIG: ''
      RELEASE_TAG: mt3600be-minimal
      ENABLE_RELEASE: true
      ENABLE_ARTIFACT: true
