name: MT3600BE-FULL

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_NAME: MT3600BE-FULL
      WRT_REPO: coolsnowwolf/lede
      WRT_BRANCH: master
      DEVICE_CONFIG: Config/MT3600BE-MINIMAL.txt
      GENERAL_CONFIG: Config/GENERAL-FULL.txt
      RELEASE_TAG: full
      ENABLE_RELEASE: true
      ENABLE_ARTIFACT: true
    secrets: inherit
    
