name: MT3600BE-MINIMAL

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_NAME: MT3600BE-MINIMAL
      WRT_REPO: coolsnowwolf/lede
      WRT_BRANCH: master
      WRT_COMMIT: 6c3097f
      DEVICE_CONFIG: Config/MT3600BE-MINIMAL.txt
      RELEASE_TAG: mt3600be-minimal
      ENABLE_RELEASE: false
      ENABLE_ARTIFACT: true
      BUILD_THREADS: '4'
    secrets: inherit
