name: MT3600BE-LATEST

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_NAME: MT3600BE-LATEST
      WRT_REPO: coolsnowwolf/lede
      WRT_BRANCH: master

      DEVICE_CONFIG: Config/MT3600BE-MINIMAL.txt
      RELEASE_TAG: latest

      ENABLE_RELEASE: false
      ENABLE_ARTIFACT: true

    secrets: inherit
