name: MT3600BE-LATEST

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_NAME: MT3600BE-LATEST
      WRT_REPO: coolsnowwolf/lede
      WRT_BRANCH: master
      WRT_CONFIG: Config/MT3600BE-MINIMAL.txt
      WRT_RELEASE: false
      WRT_ARTIFACT: true
    secrets: inherit
